swagger: "2.0"
info:
  title: Twitter Clone API
  version: 1.0.0
  description: Twitter Clone API仕様
host: localhost:8080
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      displayName:
        type: string
      bio:
        type: string
      avatarUrl:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Tweet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      content:
        type: string
      userId:
        type: integer
        format: int64
      user:
        $ref: "#/definitions/User"
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string
      user:
        $ref: "#/definitions/User"

paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: ユーザー登録
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - username
              - email
              - password
            properties:
              username:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: 登録成功
          schema:
            $ref: "#/definitions/User"
        400:
          description: 不正なリクエスト
          schema:
            $ref: "#/definitions/Error"

  /auth/login:
    post:
      tags:
        - auth
      summary: ログイン
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: ログイン成功
          schema:
            type: object
            properties:
              token:
                type: string
              user:
                $ref: "#/definitions/User"
        401:
          description: 認証エラー
          schema:
            $ref: "#/definitions/Error"

  /tweets:
    get:
      tags:
        - tweets
      summary: ツイート一覧取得
      security:
        - Bearer: []
      parameters:
        - in: query
          name: page
          type: integer
          default: 1
        - in: query
          name: limit
          type: integer
          default: 20
      responses:
        200:
          description: 成功
          schema:
            type: array
            items:
              $ref: "#/definitions/Tweet"
    post:
      tags:
        - tweets
      summary: ツイート投稿
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - content
            properties:
              content:
                type: string
      responses:
        201:
          description: 投稿成功
          schema:
            $ref: "#/definitions/Tweet"
        400:
          description: 不正なリクエスト
          schema:
            $ref: "#/definitions/Error"
        401:
          description: 認証エラー
          schema:
            $ref: "#/definitions/Error"
        500:
          description: サーバーエラー
          schema:
            $ref: "#/definitions/Error"

  /tweets/{tweetId}:
    get:
      tags:
        - tweets
      summary: 特定のツイートを取得
      security:
        - Bearer: []
      parameters:
        - in: path
          name: tweetId
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: 成功
          schema:
            $ref: "#/definitions/Tweet"
        404:
          description: ツイートが見つかりません
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - tweets
      summary: ツイートを削除
      security:
        - Bearer: []
      parameters:
        - in: path
          name: tweetId
          type: integer
          format: int64
          required: true
      responses:
        204:
          description: 削除成功
        401:
          description: 認証エラー
          schema:
            $ref: "#/definitions/Error"
        403:
          description: 権限エラー
          schema:
            $ref: "#/definitions/Error"

  /tweets/{tweetId}/like:
    post:
      tags:
        - tweets
      summary: ツイートにいいねをする
      security:
        - Bearer: []
      parameters:
        - in: path
          name: tweetId
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: いいね成功
        401:
          description: 認証エラー
          schema:
            $ref: "#/definitions/Error"
    delete:
      tags:
        - tweets
      summary: いいねを取り消す
      security:
        - Bearer: []
      parameters:
        - in: path
          name: tweetId
          type: integer
          format: int64
          required: true
      responses:
        204:
          description: いいね取り消し成功
        401:
          description: 認証エラー
          schema:
            $ref: "#/definitions/Error"

  /users/{userId}/tweets:
    get:
      tags:
        - tweets
        - users
      summary: 特定のユーザーのツイート一覧を取得
      security:
        - Bearer: []
      parameters:
        - in: path
          name: userId
          type: integer
          format: int64
          required: true
        - in: query
          name: page
          type: integer
          default: 1
        - in: query
          name: limit
          type: integer
          default: 20
      responses:
        200:
          description: 成功
          schema:
            type: array
            items:
              $ref: "#/definitions/Tweet"
        404:
          description: ユーザーが見つかりません
          schema:
            $ref: "#/definitions/Error"
